Task 6
OlgaKorolRC/KorolRingCentralTraining- pull request #3
Opened 2020-12-13 17:16 UTC by OlgaKorolRC

Task 6

2020-12-16 18:18 UTC, VeryBadProgrammer requested changes

2020-12-16 18:18 UTC, VeryBadProgrammer commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        Object[] byciclesArray = newBicycleList.toArray();
выглядит сложно, то есть ты создаешь новый объект,чтобы бежать по нему и удалять элементы из другого объекта
почему бы просто не бежать по одному объекту?
тогда если объект удален, не делать плюс один,а остаться на этой позиции

2020-12-16 18:18 UTC, VeryBadProgrammer commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        for (int i = 0; i < valueInArray; i++) {
а если вместо valueInArray использовать size arrayNumbers  не будет работать?

2020-12-25 13:14 UTC, OlgaKorolRC commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        Object[] byciclesArray = newBicycleList.toArray();
Если я в 39 строке использую 
for (Object i:newBicycleList.toArray())
то вижу ошибку 
Exception in thread "main" java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [LGenericsAndCollections.Bycicle; ([Ljava.lang.Object; is in module java.base of loader 'bootstrap'; [LGenericsAndCollections.Bycicle; is in unnamed module of loader 'app')
	at GenericsAndCollections.MainClass.main(MainClass.java:39) 
а других версий я не придумала

2020-12-25 13:15 UTC, OlgaKorolRC commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        for (int i = 0; i < valueInArray; i++) {
Думаю что будет работать, у меня была переменная для этого размера и я использовала её. Хорошей практикой считается использовать size?

2020-12-25 13:18 UTC, VeryBadProgrammer commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        for (int i = 0; i < valueInArray; i++) {
лучше использовать foreach,но если еще не проходили,то в строке int valueInArray = 10; не хардкодить значение, а использовтаь size,так как размер может меняться и не всегда хочется обдумывать это

2020-12-25 18:07 UTC, OlgaKorolRC commented on Korol_T6/src/GenericsAndCollections/GenericsAndCollections/MainClass.java
> +        for (int i = 0; i < valueInArray; i++) {
Обновила

2020-12-25 21:23 UTC, VeryBadProgrammer approved these changes

2021-01-26 19:13 UTC, merged