Create new branch for Zoo
OlgaKorolRC/KorolRingCentralTraining- pull request #4
Opened 2020-12-21 17:34 UTC by OlgaKorolRC

Pull request for Task 7 with Zoo

2020-12-22 15:38 UTC, VeryBadProgrammer requested changes

2020-12-22 15:38 UTC, VeryBadProgrammer commented on Task7/src/AnimalPackage/Zoo.java
> +    static HashSet<PetAnimal> fillCollectionWithPetAnimals(HashSet collectionWithPetAnimals, ArrayList name) {
обязательно ли тут HashSet ставить,можно ли поставить set.
И знаешь разницу между HashSet  and TreeSet?
почему не второе выбрала?

2020-12-22 15:38 UTC, VeryBadProgrammer commented on Task7/src/AnimalPackage/Zoo.java
> +        int numberAnimals = new Random(0).nextInt(4) + 1;
а если написать new Random(1).nextInt(5) это тоже самое или нет?

2020-12-25 13:10 UTC, OlgaKorolRC commented on Task7/src/AnimalPackage/Zoo.java
> +    static HashSet<PetAnimal> fillCollectionWithPetAnimals(HashSet collectionWithPetAnimals, ArrayList name) {
Нет, не обязательно (можно было например TreeSet). Set это семейство - поэтому поставить нельзя. 
Да, знаю: TreeSet отсортирован, но в этом задании не видела смысла его использовать поэтому взяла HashSet

2020-12-25 13:12 UTC, OlgaKorolRC commented on Task7/src/AnimalPackage/Zoo.java
> +        int numberAnimals = new Random(0).nextInt(4) + 1;
Да, тоже самое и в других задания я так и делала, но тут что-то пошло не так. (Всегда получается ноль - скриншот прикрепить не знаю как)

2020-12-25 13:16 UTC, VeryBadProgrammer approved these changes

2020-12-25 18:07 UTC, merged